name: Push Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply approved plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download branch_name file
        uses: actions/download-artifact@v4
        with:
          name: branch_name

      - name: set branch_name as env var
        run: BRANCH_NAME=`cat branch_name.txt`

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: .
          target: local_file.${{ env.BRANCH_NAME }}
