name: PR Plan

on:
  [pull_request]
# on:
#   push:
#     branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: terraform plan
      #   uses: dflook/terraform-plan@v1
      #   with:
      #     path: .
      #     # target: local_file.${{ github.event.pull_request.head.ref }}

      # - name: $github
      #   run: echo "$GITHUB_CONTEXT"
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}

      # - name: test body
      #   run: echo ${{ github.event.pull_request.body }}

      # - name: test title
      #   run: echo ${{ github.event.pull_request.title }}

      - name: test title 2
        run: |
          echo "CUSTOMER=$(echo ${{ github.event.pull_request.title }} | cut -d ' ' -f2)" >> $GITHUB_ENV

      - name: test var
        run: echo $CUSTOMER

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .
          target: local_file.${{ env.CUSTOMER }}

      - name: test contains
        if: "contains(${{ github.event.pull_request.title }}, 'customer: ')"
        run: |
          echo "contains 'customer: '"

      - name: test not contains
        if: "!contains(${{ github.event.pull_request.title }}, 'customer: ')"
        run: |
          echo "not contains 'customer: '"
