name: PR Plan

on:
  [pull_request]
# on:
#   push:
#     branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .
          target: local_file.${{ github.event.pull_request.head.ref }}

      - name: Store branch name
        run: echo ${{ github.event.pull_request.head.ref }} > branch_name.txt

      - name: Upload branch_name file
        uses: actions/upload-artifact@v4
        with:
          name: branch_name
          path: branch_name.txt
          retention-days: 7
