name: PR Plan

on:
  [pull_request]
# on:
#   push:
#     branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .
          # target: local_file.${{ github.event.pull_request.head.ref }}

      - name: $github
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: test
        run: echo ${{ github.event.pull_request.title }}
